multi_gpu: True
# multi_gpu: False
verbose: True

is_train: True
log: True

epoch_begin: 0
epoch_num: 1000
checkpoint: 100

batch_size: 128
num_workers: 4

dataset_dir: /apdcephfs/share_1330077/wallyliang/amass/gmp
save_dir: ./outputs/re_gmp_glamr_rep

learning_rate: 0.0001
weight_decay: 0.0001
l1_loss: False
lambda_v: 1
lambda_up: 1
lambda_trans: 1
lambda_contacts: 0.5

use_traj_rep: true

data:
    fps: 30
    clip_length: 128
    gender: male
    up: z
    normalize: ['pos', 'velocity', 'rot6d', 'angular']

global_motion:
    activation: relu
    channel_base: 15 # 3(pos) + 3(vel) + 6(rot) + 3(ang)
    out_channels: 19 # 11 + 8
    # out_channels: 12
    use_residual_blocks: True
    kernel_size: 15
    num_layers: 5
    skeleton_dist: 1
    extra_conv: 0
    padding_mode: reflect
    skeleton_pool: mean

scheduler:
    name: